(function(){
  const FAVORITES_KEY='aePluginFavorites',EDIT_FAVORITES_KEY='aeEditFavorites',THEME_KEY='theme',VISITS_KEY='aeSiteVisits',EDIT_SUBMISSIONS_KEY='aeEditSubmissions',RATE_KEY='aeLastSubmitTimes';
  const page=document.body.dataset.page||'home';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const SUPABASE_PUBLIC={url:'https://qfugshwpslhdgrogrcyl.supabase.co',anonKey:['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9','eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmdWdzaHdwc2xoZGdyb2dyY3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5MzY2ODQsImV4cCI6MjA5NDUxMjY4NH0','9mV8XDbkFwBEMtf4IvqgM-tccZrA0_SXO8eXiuRg4i0'].join('.')};
  function injectUiFixes(){if($('#uiFixes'))return;const st=document.createElement('style');st.id='uiFixes';st.textContent=`
    .hero-grid,.page-hero-home,.page-hero-home .container{overflow:visible!important}.stable-visual{height:500px!important;min-height:500px!important;overflow:visible!important;contain:layout!important;padding:56px!important;margin:-56px!important;isolation:isolate}.visual-float-ae{left:6%!important;top:10%!important;z-index:3}.visual-float-plugin{right:5%!important;top:18%!important;z-index:2}.visual-float-download{left:43%!important;bottom:7%!important;z-index:1}.visual-element{box-shadow:0 34px 95px rgba(99,102,241,.48)!important}.visual-element:hover{box-shadow:0 44px 110px rgba(99,102,241,.58)!important}
    .plugin-detail-content .hero-actions{align-items:center!important;gap:14px!important;flex-wrap:wrap!important}.plugin-detail-content .hero-actions .btn.favorite-btn,.hero-actions .btn.favorite-btn{width:auto!important;min-width:168px!important;height:auto!important;min-height:52px!important;padding:14px 18px!important;border-radius:16px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:10px!important;flex:0 0 auto!important;white-space:nowrap!important;line-height:1!important;font-size:.96rem!important;background:var(--surface)!important;color:var(--text)!important;border-color:var(--border)!important;box-shadow:var(--shadow-soft)!important}.plugin-detail-content .hero-actions .btn.favorite-btn i,.hero-actions .btn.favorite-btn i{width:auto!important;height:auto!important;margin:0!important;line-height:1!important}.plugin-detail-content .hero-actions .btn.favorite-btn.active,.hero-actions .btn.favorite-btn.active{color:#ef4444!important;background:rgba(239,68,68,.12)!important;border-color:rgba(239,68,68,.28)!important}.plugin-detail-content .hero-actions .btn.favorite-btn:hover,.hero-actions .btn.favorite-btn:hover{transform:translateY(-2px)!important;box-shadow:var(--shadow)!important}
    .catalog-panel .search-wrap{position:relative!important;display:flex!important;align-items:center!important;width:100%!important;min-height:58px!important;background:linear-gradient(180deg,var(--surface-2),color-mix(in srgb,var(--surface-2) 86%,var(--primary) 14%))!important;border:1px solid var(--border)!important;border-radius:18px!important;padding:0 56px 0 50px!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 12px 28px rgba(0,0,0,.12)!important;overflow:hidden!important;transition:var(--transition)!important}.catalog-panel .search-wrap:focus-within{border-color:rgba(99,102,241,.58)!important;box-shadow:0 0 0 4px rgba(99,102,241,.14),0 16px 34px rgba(0,0,0,.16)!important}.catalog-panel .search-wrap>i{position:absolute!important;left:18px!important;top:50%!important;transform:translateY(-50%)!important;color:var(--primary)!important;font-size:1.05rem!important;pointer-events:none!important;z-index:2!important}.catalog-panel .search-wrap input{width:100%!important;height:58px!important;border:0!important;outline:0!important;background:transparent!important;color:var(--text)!important;font-size:1rem!important;font-weight:800!important;line-height:58px!important;min-width:0!important;appearance:none!important;box-shadow:none!important}.catalog-panel .search-wrap input::placeholder{color:var(--muted)!important;opacity:.76!important;font-weight:700!important}.catalog-panel .search-wrap button,#clearEditSearch{position:absolute!important;right:10px!important;top:50%!important;transform:translateY(-50%)!important;width:38px!important;height:38px!important;border:1px solid var(--border)!important;background:var(--surface)!important;color:var(--muted)!important;border-radius:13px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;cursor:pointer!important;font-size:.95rem!important;transition:var(--transition)!important;box-shadow:0 8px 18px rgba(0,0,0,.12)!important;z-index:3!important}.catalog-panel .search-wrap button:hover,#clearEditSearch:hover{color:#fff!important;background:var(--primary)!important;border-color:var(--primary)!important;box-shadow:0 12px 24px rgba(99,102,241,.28)!important}
    .field-hint{display:block;margin:6px 0 0;color:var(--muted);font-size:.84rem;font-weight:700;line-height:1.35}.field-hint b{color:var(--primary)}.version-selector{margin:22px 0 4px;border:1px solid var(--border);border-radius:20px;background:var(--surface);box-shadow:var(--shadow-soft);max-width:560px;overflow:hidden}.version-selector summary{list-style:none;cursor:pointer;padding:16px 18px;display:flex;align-items:center;justify-content:space-between;gap:14px;font-weight:900;color:var(--text)}.version-selector summary::-webkit-details-marker{display:none}.version-selector summary span{display:flex;align-items:center;gap:10px}.version-selector summary .chevron{transition:transform .2s ease}.version-selector[open] summary .chevron{transform:rotate(180deg)}.version-selector-body{padding:0 18px 18px}.version-selector-list{display:flex;flex-wrap:wrap;gap:10px}.version-option{border:1px solid var(--border);background:var(--surface-2);color:var(--text);border-radius:14px;padding:12px 14px;font-weight:900;display:inline-flex;align-items:center;gap:8px;transition:var(--transition);text-decoration:none}.version-option.active{background:linear-gradient(135deg,var(--primary),#8b5cf6);border-color:transparent;color:#fff}.version-option:hover{transform:translateY(-2px);box-shadow:var(--shadow-soft)}.version-note{margin-top:12px;color:var(--muted);font-size:.9rem;font-weight:700}.version-note.success{color:#22c55e}.version-note.error{color:#ef4444}
    .cancel-submission-btn,.edit-favorite-btn,.report-link-btn,.request-plugin-btn,.admin-action-btn{border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:14px;padding:10px 13px;font-weight:900;display:inline-flex;align-items:center;justify-content:center;gap:8px;cursor:pointer;transition:var(--transition);text-decoration:none}.cancel-submission-btn{border-color:rgba(239,68,68,.28);background:rgba(239,68,68,.12);color:#ef4444}.cancel-submission-btn:hover,.edit-favorite-btn:hover,.report-link-btn:hover,.request-plugin-btn:hover,.admin-action-btn:hover{transform:translateY(-2px);box-shadow:var(--shadow-soft)}.cancel-submission-btn:disabled,.admin-action-btn:disabled{opacity:.6;cursor:not-allowed;transform:none}.edit-favorite-btn.active{color:#ef4444;background:rgba(239,68,68,.12);border-color:rgba(239,68,68,.28)}.pending-badge{display:inline-flex;align-items:center;gap:7px;border:1px solid rgba(245,158,11,.28);background:rgba(245,158,11,.12);color:#f59e0b;border-radius:999px;padding:7px 10px;font-size:.82rem;font-weight:900}
    .edit-thumb.thumb-broken img,.edit-detail-thumb.thumb-broken img{display:none!important}.edit-thumb-fallback{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:radial-gradient(circle at 30% 20%,rgba(99,102,241,.28),transparent 42%),var(--surface-2);color:var(--text);font-weight:900;text-align:center;padding:18px}.edit-thumb-fallback i{font-size:2rem;color:var(--primary)}.request-modal{position:fixed;inset:0;background:rgba(0,0,0,.62);display:flex;align-items:center;justify-content:center;padding:20px;z-index:9999}.request-modal[hidden]{display:none}.request-modal-card{width:min(560px,100%);background:var(--surface);border:1px solid var(--border);border-radius:24px;padding:24px;box-shadow:var(--shadow);position:relative}.request-modal-close{position:absolute;right:14px;top:14px;width:36px;height:36px;border-radius:12px;border:1px solid var(--border);background:var(--surface-2);color:var(--text);cursor:pointer}.request-modal-card label{display:block;margin:14px 0;font-weight:900}.request-modal-card input,.request-modal-card textarea{width:100%;margin-top:8px}.inline-report-form{margin-top:18px;padding:16px;border:1px solid var(--border);border-radius:18px;background:var(--surface)}.inline-report-form label{display:block;font-weight:900}.inline-report-form input{width:100%;margin:8px 0 12px}.stats-chip{display:inline-flex!important;align-items:center;gap:7px;border:1px solid var(--border);background:var(--surface);border-radius:999px;padding:7px 10px;font-weight:900;color:var(--muted)}
    .admin-grid{display:grid;grid-template-columns:1fr;gap:22px;margin-top:24px}.admin-list{display:grid;gap:12px}.admin-item{border:1px solid var(--border);border-radius:18px;background:var(--surface-2);padding:14px}.admin-item h3{margin-bottom:8px}.admin-item p{color:var(--muted);margin:4px 0}.admin-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.admin-action-btn.approve{background:rgba(16,185,129,.12);border-color:rgba(16,185,129,.3);color:#10b981}.admin-action-btn.reject,.admin-action-btn.delete{background:rgba(239,68,68,.12);border-color:rgba(239,68,68,.3);color:#ef4444}.admin-action-btn.done{background:rgba(99,102,241,.12);border-color:rgba(99,102,241,.3);color:var(--primary)}
    @media(max-width:900px){.stable-visual{height:390px!important;min-height:390px!important;padding:38px!important;margin:-38px!important}.visual-float-ae{left:4%!important;top:9%!important}.visual-float-plugin{right:4%!important;top:19%!important}.visual-float-download{left:40%!important;bottom:5%!important}.ae-card{width:164px!important;height:164px!important}.visual-element{width:122px!important;height:122px!important}.plugin-detail-content .hero-actions .btn.favorite-btn,.hero-actions .btn.favorite-btn{min-width:156px!important;min-height:50px!important}.version-selector-list{flex-direction:column}.version-option{justify-content:center;width:100%}.catalog-panel .search-wrap{min-height:54px!important;padding:0 50px 0 46px!important}.catalog-panel .search-wrap input{height:54px!important;line-height:54px!important;font-size:.94rem!important}.catalog-panel .search-wrap>i{left:16px!important}.catalog-panel .search-wrap button,#clearEditSearch{width:34px!important;height:34px!important;right:9px!important}}
  `;document.head.appendChild(st)}
  const readJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},writeJson=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const getFavorites=()=>readJson(FAVORITES_KEY,[]),saveFavorites=v=>writeJson(FAVORITES_KEY,v),getEditFavorites=()=>readJson(EDIT_FAVORITES_KEY,[]),saveEditFavorites=v=>writeJson(EDIT_FAVORITES_KEY,v);
  const sbHeaders=e=>Object.assign({apikey:SUPABASE_PUBLIC.anonKey,Authorization:`Bearer ${SUPABASE_PUBLIC.anonKey}`},e||{});
  async function sbInsert(table,payload){const r=await fetch(`${SUPABASE_PUBLIC.url}/rest/v1/${table}`,{method:'POST',headers:sbHeaders({'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text().catch(()=>'Ошибка Supabase'));return true}
  async function sbCount(table,query){const r=await fetch(`${SUPABASE_PUBLIC.url}/rest/v1/${table}?${query}&select=id`,{method:'HEAD',headers:sbHeaders({Prefer:'count=exact'})});const n=Number((r.headers.get('content-range')||'').split('/')[1]);return Number.isFinite(n)?n:0}
  function canSubmit(n,d){const x=readJson(RATE_KEY,{}),now=Date.now();if(x[n]&&now-x[n]<d)return Math.ceil((d-(now-x[n]))/1000);x[n]=now;writeJson(RATE_KEY,x);return 0}
  function setStatus(sel,msg,type){const s=$(sel);if(!s)return;s.hidden=false;s.textContent=msg;s.classList.remove('success','error');if(type)s.classList.add(type)}
  function esc(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

  function syncFavoriteUI(){const fav=getFavorites();$$('#favoriteCount').forEach(e=>e.textContent=fav.length);$$('.favorite-btn[data-id]').forEach(b=>{const a=fav.includes(b.dataset.id),w=b.classList.contains('btn');b.classList.toggle('active',a);b.innerHTML=a?`<i class="fas fa-heart"></i>${w?' В избранном':''}`:`<i class="far fa-heart"></i>${w?' В избранное':''}`});syncEditFavorites()}
  function toggleFavorite(id){const a=getFavorites(),i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);saveFavorites(a);syncFavoriteUI();filterCatalog()}
  function syncEditFavorites(){const fav=getEditFavorites();$$('.edit-favorite-btn[data-edit-id]').forEach(b=>{const a=fav.includes(b.dataset.editId);b.classList.toggle('active',a);b.innerHTML=a?'<i class="fas fa-heart"></i> В избранном':'<i class="far fa-heart"></i> В избранное'});filterCommunity()}
  function toggleEditFavorite(id){const a=getEditFavorites(),i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);saveEditFavorites(a);syncEditFavorites()}
  function applyTheme(d){document.documentElement.classList.toggle('dark-mode',d);document.documentElement.classList.toggle('light-mode',!d);document.body.classList.toggle('dark-mode',d);document.body.classList.toggle('light-mode',!d);const i=$('#themeToggle i');if(i)i.className=d?'fas fa-sun':'fas fa-moon'}
  function initTheme(){const s=localStorage.getItem(THEME_KEY);applyTheme(s?s==='dark':true)}
  function initVisits(){const v=readJson(VISITS_KEY,{});v.total=(v.total||0)+1;v[page]=(v[page]||0)+1;writeJson(VISITS_KEY,v);$$('#localVisitCount').forEach(e=>e.textContent=v.total)}
  function setupReveals(){const items=$$('.reveal:not(.revealed)');if(!('IntersectionObserver'in window)){items.forEach(x=>x.classList.add('revealed'));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');o.unobserve(e.target)}}),{threshold:.08});items.forEach(x=>o.observe(x))}

  function cardText(c){return[c.dataset.name||'',c.textContent||''].join(' ').toLowerCase()}
  function sortCards(cards,sort){return cards.sort((a,b)=>{const an=a.dataset.name||'',bn=b.dataset.name||'';if(sort==='az')return an.localeCompare(bn,'ru');if(sort==='available')return Number(b.dataset.status==='available')-Number(a.dataset.status==='available')||an.localeCompare(bn,'ru');if(sort==='size')return Number(a.dataset.size||0)-Number(b.dataset.size||0);if(sort==='new')return Number(/нов/i.test(b.textContent))-Number(/нов/i.test(a.textContent))||an.localeCompare(bn,'ru');return Number(/популяр/i.test(b.textContent))-Number(/популяр/i.test(a.textContent))||Number(b.dataset.status==='available')-Number(a.dataset.status==='available')||an.localeCompare(bn,'ru')})}
  function filterCatalog(){const g=$('#pluginsGrid');if(!g)return;const cards=$$('[data-plugin-card]',g),q=($('#pluginSearch')?.value||'').trim().toLowerCase(),cat=$('#categoryFilters .filter-btn.active')?.dataset.category||'all',fo=$('#favoritesOnly')?.classList.contains('active'),fav=getFavorites();let n=0;cards.forEach(c=>{const show=(cat==='all'||c.dataset.category===cat)&&(!q||cardText(c).includes(q))&&(!fo||fav.includes(c.dataset.id));c.style.display=show?'':'none';c.hidden=!show;if(show)n++});sortCards(cards,$('#sortPlugins')?.value||'popular').forEach(c=>g.appendChild(c));if($('#resultCount'))$('#resultCount').textContent=`Найдено: ${n}`;if($('#activeFilterLabel'))$('#activeFilterLabel').textContent=($('#categoryFilters .filter-btn.active')?.textContent||'Все категории')+(fo?' · избранное':'');if($('#emptyState'))$('#emptyState').hidden=n!==0}
  function initCatalog(){const p=new URLSearchParams(location.search);if(p.get('favorites')==='1')$('#favoritesOnly')?.classList.add('active');document.addEventListener('input',e=>{if(e.target&&e.target.id==='pluginSearch')filterCatalog()});$('#pluginSearch')?.addEventListener('keyup',filterCatalog);$('#clearSearch')?.addEventListener('click',()=>{const i=$('#pluginSearch');if(i){i.value='';i.focus()}filterCatalog()});$('#sortPlugins')?.addEventListener('change',filterCatalog);$('#favoritesOnly')?.addEventListener('click',()=>{$('#favoritesOnly')?.classList.toggle('active');filterCatalog()});$('#categoryFilters')?.addEventListener('click',e=>{const b=e.target.closest('.filter-btn');if(!b)return;$$('.filter-btn',$('#categoryFilters')).forEach(x=>x.classList.remove('active'));b.classList.add('active');filterCatalog()});filterCatalog()}

  function filterCommunity(){const g=$('#communityGrid');if(!g)return;const q=($('#editSearch')?.value||'').trim().toLowerCase(),a=$('#editFilters .filter-btn.active')?.dataset.platform||'all',fo=$('#editFavoritesOnly')?.classList.contains('active'),fav=getEditFavorites();let n=0;$$('.edit-card',g).forEach(c=>{const t=c.textContent.toLowerCase(),p=t.includes('tiktok')?'tiktok':t.includes('youtube')?'youtube':'video',id=c.dataset.id||c.querySelector('.edit-favorite-btn')?.dataset.editId;const show=(a==='all'||p===a)&&(!q||t.includes(q))&&(!fo||fav.includes(id));c.hidden=!show;if(show)n++});if($('#editCount'))$('#editCount').textContent=`Работ: ${n}`;if($('#communityEmpty'))$('#communityEmpty').hidden=n!==0}
  function initCommunity(){syncEditFavorites();document.addEventListener('input',e=>{if(e.target&&e.target.id==='editSearch')filterCommunity()});$('#clearEditSearch')?.addEventListener('click',()=>{const i=$('#editSearch');if(i){i.value='';i.focus()}filterCommunity()});$('#editFilters')?.addEventListener('click',e=>{const b=e.target.closest('.filter-btn');if(!b)return;$$('.filter-btn',$('#editFilters')).forEach(x=>x.classList.remove('active'));b.classList.add('active');filterCommunity()});$('#editFavoritesOnly')?.addEventListener('click',()=>{$('#editFavoritesOnly')?.classList.toggle('active');filterCommunity()});filterCommunity()}
  function initBrokenThumbFallback(){document.addEventListener('error',e=>{const img=e.target;if(!img||img.tagName!=='IMG'||!img.closest('.edit-thumb,.edit-detail-thumb'))return;const h=img.closest('.edit-thumb,.edit-detail-thumb');h.classList.add('thumb-broken');if(!h.querySelector('.edit-thumb-fallback')){const d=document.createElement('div');d.className='edit-thumb-fallback';d.innerHTML='<i class="fas fa-video"></i><span>Превью недоступно</span>';h.appendChild(d)}},true)}

  function readSubmissions(){return readJson(EDIT_SUBMISSIONS_KEY,[])}function saveSubmissions(v){writeJson(EDIT_SUBMISSIONS_KEY,v)}
  function renderSubmissions(){const g=$('#mySubmissionsGrid');if(!g)return;const list=readSubmissions();g.innerHTML=list.map((it,i)=>`<article class="edit-card revealed"><div class="edit-body"><div class="badge-stack"><span class="pending-badge"><i class="fas fa-clock"></i> На проверке</span></div><h3>${esc(it.title)}</h3><p>${esc(it.description||'Пользовательская работа After Effects.')}</p><div class="edit-meta"><span><i class="fas fa-user"></i> ${esc(it.author)}</span>${it.plugins?`<span><i class="fas fa-plug"></i> ${esc(it.plugins)}</span>`:''}</div></div><div class="edit-actions"><a class="details-btn" href="${esc(it.url)}" target="_blank" rel="noopener"><i class="fas fa-up-right-from-square"></i> Открыть</a><button class="cancel-submission-btn" data-cancel-index="${i}" type="button"><i class="fas fa-ban"></i> Отменить</button></div></article>`).join('');const e=$('#mySubmissionsEmpty');if(e)e.hidden=list.length!==0}
  function inferPlatform(v){v=String(v||'').toLowerCase();return v.includes('youtube.com')||v.includes('youtu.be')?'youtube':v.includes('tiktok.com')?'tiktok':'video'}
  async function cancelSubmission(i,b){const list=readSubmissions(),it=list[i];if(!it||!confirm('Отменить эту заявку?'))return;try{if(b)b.disabled=true;const r=await fetch('/api/edit-submissions/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:it.serverId,url:it.url,title:it.title,author:it.author})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Не удалось отменить заявку');list.splice(i,1);saveSubmissions(list);renderSubmissions();setStatus('#submitStatus','Заявка отменена.','success')}catch(e){setStatus('#submitStatus',e.message,'error');if(b)b.disabled=false}}
  function initSubmit(){renderSubmissions();document.addEventListener('click',e=>{const b=e.target.closest('.cancel-submission-btn');if(b)cancelSubmission(Number(b.dataset.cancelIndex),b)});$('#editSubmitForm')?.addEventListener('submit',async e=>{e.preventDefault();const wait=canSubmit('edit',30000);if(wait)return setStatus('#submitStatus',`Подожди ${wait} сек. перед новой отправкой.`,'error');const f=e.target,btn=f.querySelector('button[type="submit"]'),item={url:$('#editUrl')?.value||'',thumb:$('#editThumb')?.value||'',title:$('#editTitle')?.value||'Без названия',author:$('#editAuthor')?.value||'Автор',plugins:$('#editPlugins')?.value||'',description:$('#editDescription')?.value||'',platform:inferPlatform($('#editUrl')?.value||'')};try{if(btn)btn.disabled=true;setStatus('#submitStatus','Отправляю заявку...',null);const r=await fetch('/api/edit-submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Не удалось отправить заявку');const row=Array.isArray(d)?d[0]:d,list=readSubmissions();list.unshift({id:'local-'+Date.now(),serverId:row&&row.id?row.id:null,...item,created:new Date().toISOString()});saveSubmissions(list);f.reset();renderSubmissions();setStatus('#submitStatus','Заявка отправлена на проверку.','success')}catch(err){setStatus('#submitStatus',err.message,'error')}finally{if(btn)btn.disabled=false}})}

  function initFlowVersionSelector(){if(location.pathname!=='/plugin/flow')return;const a=$('.plugin-detail-content .hero-actions'),dl=$('.plugin-detail-content .hero-actions .btn-primary');if(!a||!dl||$('#flowVersionSelector'))return;const box=document.createElement('details');box.id='flowVersionSelector';box.className='version-selector reveal revealed';box.innerHTML=`<summary><span><i class="fas fa-code-branch"></i> Выбрать версию Flow</span><i class="fas fa-chevron-down chevron"></i></summary><div class="version-selector-body"><div class="version-selector-list"><a class="version-option" href="/download/flow?version=v141" target="_blank" rel="noopener"><i class="fas fa-download"></i> Скачать v1.4.1</a><a class="version-option active" href="/download/flow" target="_blank" rel="noopener"><i class="fas fa-check-circle"></i> Скачать v1.5.2</a></div><div class="version-note">Нажми на нужную версию. Основная кнопка скачивания ведёт на Flow v1.5.2.</div></div>`;a.parentNode.insertBefore(box,a);dl.innerHTML='<i class="fas fa-download"></i> Скачать v1.5.2'}
  const pluginId=()=>{const m=location.pathname.match(/^\/plugin\/([^/]+)/);return m?decodeURIComponent(m[1]):''};
  function initPluginReport(){const id=pluginId();if(!id)return;const name=$('h1')?.textContent?.replace(/ для After Effects/i,'').trim()||id;document.addEventListener('click',e=>{if(e.target.closest('.report-link-btn'))$('#pluginReportForm')&&($('#pluginReportForm').hidden=!$('#pluginReportForm').hidden)});$('#pluginReportForm')?.addEventListener('submit',async e=>{e.preventDefault();const wait=canSubmit('report',30000);if(wait)return setStatus('#pluginReportStatus',`Подожди ${wait} сек.`,'error');try{setStatus('#pluginReportStatus','Отправляю...',null);await fetch('/api/plugin-reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plugin_id:id,plugin_name:name,message:$('#pluginReportMessage')?.value||null})}).then(async r=>{if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Ошибка')});e.target.reset();setStatus('#pluginReportStatus','Жалоба отправлена. Спасибо!','success')}catch(err){setStatus('#pluginReportStatus',err.message,'error')}})}
  function initPluginRequest(){const f=$('#pluginRequestForm');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const wait=canSubmit('pluginRequest',30000);if(wait)return setStatus('#pluginRequestStatus',`Подожди ${wait} сек.`,'error');try{setStatus('#pluginRequestStatus','Отправляю...',null);const r=await fetch('/api/plugin-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#requestPluginName')?.value||'',source_url:$('#requestPluginUrl')?.value||null,comment:$('#requestPluginComment')?.value||null})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Ошибка');e.target.reset();setStatus('#pluginRequestStatus','Запрос отправлен.','success')}catch(err){setStatus('#pluginRequestStatus',err.message,'error')}})}
  async function initPublicStats(){const id=pluginId();try{if(id){await sbInsert('site_events',{event_type:'plugin_view',plugin_id:id,path:location.pathname});const [v,d]=await Promise.all([sbCount('site_events',`event_type=eq.plugin_view&plugin_id=eq.${encodeURIComponent(id)}`),sbCount('site_events',`event_type=eq.download&plugin_id=eq.${encodeURIComponent(id)}`)]);const m=$('.detail-meta');if(m&&!$('#publicStats')){const s=document.createElement('span');s.id='publicStats';s.className='stats-chip';s.innerHTML=`<i class="fas fa-eye"></i> ${v} просмотров · <i class="fas fa-download"></i> ${d} скачиваний`;m.appendChild(s)}}}catch(_){}document.addEventListener('click',async e=>{const a=e.target.closest('a[href^="/download/"]');if(!a)return;const m=a.getAttribute('href').match(/^\/download\/([^?]+)/);if(m)try{await sbInsert('site_events',{event_type:'download',plugin_id:decodeURIComponent(m[1]),path:a.getAttribute('href')})}catch(_){}})}

  function adminHeaders(){return{'Content-Type':'application/json','x-admin-pin':$('#adminPin')?.value||''}}
  function adminItem(title,body,actions){return`<article class="admin-item"><h3>${esc(title)}</h3>${body}<div class="admin-actions">${actions}</div></article>`}
  function renderAdmin(data){
    const sub=$('#adminSubmissions'),rep=$('#adminReports'),req=$('#adminRequests');
    if(sub)sub.innerHTML=(data.submissions||[]).map(x=>adminItem(x.title||'Без названия',`<p><b>Автор:</b> ${esc(x.author||'')}</p><p><b>URL:</b> <a href="${esc(x.url||'#')}" target="_blank">открыть</a></p><p>${esc(x.description||'')}</p>`,`<button class="admin-action-btn approve" data-admin-action="submission" data-id="${esc(x.id)}" data-status="approved">Одобрить</button><button class="admin-action-btn reject" data-admin-action="submission" data-id="${esc(x.id)}" data-status="rejected">Отклонить</button><button class="admin-action-btn delete" data-admin-action="submission-delete" data-id="${esc(x.id)}">Удалить</button>`)).join('')||'<p class="muted">Нет pending-заявок.</p>';
    if(rep)rep.innerHTML=(data.reports||[]).map(x=>adminItem(x.plugin_name||x.plugin_id||'Плагин',`<p><b>ID:</b> ${esc(x.plugin_id||'')}</p><p>${esc(x.message||'Без комментария')}</p>`,`<button class="admin-action-btn done" data-admin-action="report" data-id="${esc(x.id)}">Закрыть</button>`)).join('')||'<p class="muted">Нет жалоб.</p>';
    if(req)req.innerHTML=(data.requests||[]).map(x=>adminItem(x.name||'Запрос',`<p>${x.source_url?`<a href="${esc(x.source_url)}" target="_blank">Источник</a>`:''}</p><p>${esc(x.comment||'')}</p>`,`<button class="admin-action-btn done" data-admin-action="request" data-id="${esc(x.id)}">Закрыть</button>`)).join('')||'<p class="muted">Нет запросов.</p>';
  }
  async function loadAdmin(){try{setStatus('#adminStatus','Загружаю...',null);const r=await fetch('/api/admin/dashboard',{headers:adminHeaders()}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Ошибка входа');$('#adminPanels').hidden=false;renderAdmin(d);setStatus('#adminStatus','Данные загружены.','success')}catch(e){setStatus('#adminStatus',e.message,'error')}}
  async function adminAction(btn){const id=btn.dataset.id,act=btn.dataset.adminAction;try{btn.disabled=true;let url='',opt={headers:adminHeaders()};if(act==='submission'){url=`/api/admin/submissions/${encodeURIComponent(id)}`;opt.method='PATCH';opt.body=JSON.stringify({status:btn.dataset.status})}if(act==='submission-delete'){if(!confirm('Удалить заявку?')){btn.disabled=false;return}url=`/api/admin/submissions/${encodeURIComponent(id)}`;opt.method='DELETE'}if(act==='report'){url=`/api/admin/plugin-reports/${encodeURIComponent(id)}`;opt.method='PATCH';opt.body=JSON.stringify({status:'done'})}if(act==='request'){url=`/api/admin/plugin-requests/${encodeURIComponent(id)}`;opt.method='PATCH';opt.body=JSON.stringify({status:'done'})}const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Ошибка действия');await loadAdmin()}catch(e){setStatus('#adminStatus',e.message,'error');btn.disabled=false}}
  function initAdminPanel(){if(page!=='admin')return;$('#adminLoadBtn')?.addEventListener('click',loadAdmin);document.addEventListener('click',e=>{const b=e.target.closest('[data-admin-action]');if(b)adminAction(b)});$('#adminPin')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();loadAdmin()}})}

  function initEvents(){
    $('#themeToggle')?.addEventListener('click',()=>{const d=!document.documentElement.classList.contains('dark-mode');applyTheme(d);localStorage.setItem(THEME_KEY,d?'dark':'light')});
    $('#menuToggle')?.addEventListener('click',()=>$('#navLinks')?.classList.toggle('open'));
    document.addEventListener('click',e=>{const b=e.target.closest('.favorite-btn[data-id]');if(b){e.preventDefault();toggleFavorite(b.dataset.id)}const eb=e.target.closest('.edit-favorite-btn[data-edit-id]');if(eb){e.preventDefault();toggleEditFavorite(eb.dataset.editId)}});
    const top=$('#backToTop');window.addEventListener('scroll',()=>top?.classList.toggle('show',window.scrollY>500));top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
  }
  document.addEventListener('DOMContentLoaded',()=>{injectUiFixes();initTheme();initVisits();initEvents();syncFavoriteUI();initFlowVersionSelector();initBrokenThumbFallback();initPluginReport();initPluginRequest();initPublicStats();initAdminPanel();if(page==='plugins')initCatalog();if(page==='community')initCommunity();if(page==='submit')initSubmit();setupReveals()});
})();
