window.AE_PLUGINS = [
  {
    "id": "after-effects-20-25",
    "name": "After Effects 20-25",
    "description": "Комплект файлов и материалов для версий After Effects 2020–2025.",
    "category": "suite",
    "categoryLabel": "Комплект",
    "package": "zip",
    "minAe": "2020",
    "version": "2020–2025",
    "size": "Обновляется",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Комплект",
    "icon": "fas fa-box-archive",
    "tags": ["комплект", "ae", "2020", "2025"],
    "updated": "Обновляется",
    "compatibility": "After Effects 2020–2025"
  },
  {
    "id": "aftercodecs",
    "name": "AfterCodecs",
    "description": "Плагин для экспорта и кодирования видео из After Effects и Media Encoder.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1QrFR1hmNC3idmFap2SoqKEr2OSqs9bjO/view?usp=drive_link",
    "badge": "Утилита",
    "icon": "fas fa-file-video",
    "tags": ["экспорт", "кодек", "рендер", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "autosway",
    "name": "AutoSway",
    "description": "Автоматическая анимация колебаний для текста, объектов и слоев с реалистичной физикой.",
    "category": "animation",
    "categoryLabel": "Анимация",
    "package": "jsx",
    "minAe": "2018",
    "version": "v2.3.0",
    "size": "3.5 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1OMLa4wbLGeJ760CqjPeOa3ooXG0uNpD1/view?usp=drive_link",
    "badge": "Скрипт",
    "icon": "fas fa-random",
    "tags": ["анимация", "jsx"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2018+ / лучше AE 2022 и новее"
  },
  {
    "id": "ballpoint",
    "name": "Ballpoint",
    "description": "Инструмент для стилизованной графики, линий и рисованных эффектов в After Effects.",
    "category": "animation",
    "categoryLabel": "Анимация",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/18COpTB3mpQShnAKr-Hwg6C6nulseA_mn/view?usp=drive_link",
    "badge": "Новый",
    "icon": "fas fa-pen-nib",
    "tags": ["анимация", "линии", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "bcc-continuum",
    "name": "BCC Continuum",
    "description": "Полный набор плагинов для визуальных эффектов, включая ретушь, стилизацию и анимацию.",
    "category": "suite",
    "categoryLabel": "Комплект",
    "package": "aex",
    "minAe": "2022",
    "version": "v2024",
    "size": "2.1 GB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1wjiCMn2cOGR0WDy1Iy2jKUhKltJN_Vl-/view?usp=drive_link",
    "badge": "Комплект",
    "icon": "fas fa-infinity",
    "tags": ["комплект", "aex", "bcc", "continuum"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2022+ / лучше AE 2022 и новее"
  },
  {
    "id": "bcc-sapphire",
    "name": "BCC Sapphire",
    "description": "Коллекция профессиональных эффектов для цветокоррекции, стилизации, свечения и переходов.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2021",
    "version": "v2024.01",
    "size": "850 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1gXX0MUQ-Cz4S75TsW4RtHnstO1CTaXog/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-sparkles",
    "tags": ["эффекты", "aex", "popular", "sapphire"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "bevelizer",
    "name": "Bevelizer",
    "description": "Плагин для создания фасок, объёма и декоративных граней у слоёв и текста.",
    "category": "3d",
    "categoryLabel": "3D",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1qJwvm_nQoe79NNwxpE9YlWCzFVYv4vk6/view?usp=drive_link",
    "badge": "3D",
    "icon": "fas fa-cube",
    "tags": ["3d", "bevel", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "bokeh",
    "name": "Bokeh",
    "description": "Создание эффектов боке и размытия с художественным контролем над формой и интенсивностью.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "v1.1.0",
    "size": "22 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1bjfHjjp4FQSr1yaMDhz8yL_e1DB6SFj-/view?usp=drive_link",
    "badge": "Эффект",
    "icon": "fas fa-tint",
    "tags": ["эффекты", "aex", "bokeh"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "clearplus",
    "name": "ClearPlus",
    "description": "Инструмент для улучшения чёткости, очистки и визуального усиления изображения.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1V_FrAeJib1m63DciWBNpB0IqIGJ98q7k/view?usp=drive_link",
    "badge": "Эффект",
    "icon": "fas fa-wand-magic-sparkles",
    "tags": ["эффекты", "clean", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "deep-glow-v1",
    "name": "Deep Glow v1",
    "description": "Версия Deep Glow v1 для создания мягкого, реалистичного свечения и неоновых эффектов.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "v1",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1orkdfgx_stkORU_DZM5OKTLYp6FsJL_-/view?usp=drive_link",
    "badge": "Glow",
    "icon": "fas fa-sun",
    "tags": ["эффекты", "glow", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "deep-glow-v2",
    "name": "Deep Glow v2",
    "description": "Версия Deep Glow v2 для реалистичного свечения, неона и ярких световых эффектов.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2021",
    "version": "v2",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1NdqsXooTDJhloO5fGENOOFRsFcNGFXPF/view?usp=drive_link",
    "badge": "Glow",
    "icon": "fas fa-sun",
    "tags": ["эффекты", "glow", "aex", "new"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "element-3d",
    "name": "Element 3D",
    "description": "Плагин для работы с 3D-объектами, материалами и сценами внутри After Effects.",
    "category": "3d",
    "categoryLabel": "3D",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1_Svv0oDkar6XAFtm3hisKu3yXVoD7y2d/view?usp=drive_link",
    "badge": "3D",
    "icon": "fas fa-cubes",
    "tags": ["3d", "element", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "ezco-crt-emulator",
    "name": "EZCO-CRT-EMULATOR",
    "description": "Эмулятор CRT-экрана для создания ретро-эффектов, сканлайнов и старого дисплея.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1aaycttBCwIS72spP4pzZ1OYk9NtJJ5r4/view?usp=drive_link",
    "badge": "Ретро",
    "icon": "fas fa-tv",
    "tags": ["crt", "ретро", "glitch", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "film-convert-nitrate",
    "name": "Film Convert Nitrate",
    "description": "Плагин для стилизации видео под киноплёнку, работы с зерном, цветом и профилями камер.",
    "category": "color",
    "categoryLabel": "Цвет",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/18GofsHWLpY3CT0tzuw2L-LK5nw99ZesL/view?usp=drive_link",
    "badge": "Цвет",
    "icon": "fas fa-film",
    "tags": ["цвет", "film", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "film-damage-pack",
    "name": "Film Damage Pack",
    "description": "Эффекты старой пленки: царапины, пыль, зернистость, мерцание.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "ffx",
    "minAe": "2020",
    "version": "v1.5.3",
    "size": "210 MB",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Эффект",
    "icon": "fas fa-video",
    "tags": ["эффекты", "ffx", "film"],
    "updated": "Обновляется",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "flow",
    "name": "Flow",
    "description": "Плагин для создания и управления кривыми анимации. В карточке объединены версии v1.4.1 и v1.5.2.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2019",
    "version": "v1.4.1 / v1.5.2",
    "size": "4.2 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1KRXEiGgy4XFaOIyMMqDtBG702uljfu43/view?usp=drive_link",
    "badge": "Выбор версии",
    "icon": "fas fa-wave-square",
    "tags": ["утилиты", "jsx", "flow", "versions"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2019+ / лучше AE 2022 и новее",
    "versions": [
      { "label": "Flow v1.4.1", "status": "available", "downloadUrl": "https://drive.google.com/file/d/1tyKN0vTzWbjKpd_eziVGAR-jKLqG9PPb/view?usp=drive_link" },
      { "label": "Flow v1.5.2", "status": "available", "downloadUrl": "https://drive.google.com/file/d/1KRXEiGgy4XFaOIyMMqDtBG702uljfu43/view?usp=drive_link" }
    ]
  },
  {
    "id": "fxaa",
    "name": "FXAA",
    "description": "Эффект сглаживания и улучшения краёв для видео и графики.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/167nT41DKD5PfDhU65q6_wxzC1ltIvWG2/view?usp=drive_link",
    "badge": "Эффект",
    "icon": "fas fa-border-all",
    "tags": ["эффекты", "fxaa", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "fxconsole",
    "name": "FXConsole",
    "description": "Маленькая утилита для быстрого вызова и добавления эффектов в Adobe After Effects.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2022",
    "version": "v1.0.5",
    "size": "1.4 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/14hDha5z5quu9WeH_FEJCBPRYbunBiN-8/view?usp=drive_link",
    "badge": "Утилита",
    "icon": "fas fa-layer-group",
    "tags": ["утилиты", "jsx"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2022+ / лучше AE 2022 и новее"
  },
  {
    "id": "glitchify",
    "name": "Glitchify",
    "description": "Набор эффектов для глитчей, цифровых искажений и динамичных переходов.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Glitch",
    "icon": "fas fa-bolt",
    "tags": ["glitch", "эффекты", "aex"],
    "updated": "Обновляется",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "heat-distortion",
    "name": "Heat Distortion",
    "description": "Эффект теплового искажения, марева и дрожания воздуха.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1srf-egNe04y68GRW5ZoTXysGMS9vGtHR/view?usp=drive_link",
    "badge": "Эффект",
    "icon": "fas fa-temperature-high",
    "tags": ["heat", "distortion", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "influx",
    "name": "Influx",
    "description": "Инструмент для создания продвинутых частиц, жидкостей и динамических симуляций.",
    "category": "particles",
    "categoryLabel": "Частицы",
    "package": "aex",
    "minAe": "2023",
    "version": "v1.8.0",
    "size": "120 MB",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Новый",
    "icon": "fas fa-water",
    "tags": ["частицы", "aex", "new"],
    "updated": "Обновляется",
    "compatibility": "After Effects 2023+ / лучше AE 2022 и новее"
  },
  {
    "id": "jpeg-glitch",
    "name": "JPEG Glitch",
    "description": "Эффект JPEG-артефактов, сжатия, цифровых ошибок и визуального шума.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1AqMyKyC67G4xJE_zZWC7NUvcXI14X7hj/view?usp=drive_link",
    "badge": "Glitch",
    "icon": "fas fa-image",
    "tags": ["jpeg", "glitch", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "mask-prompter",
    "name": "Mask Prompter",
    "description": "Инструмент для работы с масками, промптами и быстрыми выделениями в монтажном процессе.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2021",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Утилита",
    "icon": "fas fa-vector-square",
    "tags": ["mask", "jsx", "утилиты"],
    "updated": "Обновляется",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "maxon-looks-trapcode",
    "name": "Maxon Looks / Trapcode",
    "description": "Набор Maxon для стилизации, цветокоррекции, эффектов и motion graphics.",
    "category": "suite",
    "categoryLabel": "Комплект",
    "package": "aex",
    "minAe": "2021",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1v8hyREN9FILZummmurScv31pU1PDbBLY/view?usp=drive_link",
    "badge": "Комплект",
    "icon": "fas fa-gem",
    "tags": ["maxon", "looks", "trapcode", "комплект"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "mocha-pro",
    "name": "Mocha Pro",
    "description": "Мощный инструмент для трекинга, стабилизации и ротоскопинга с плоскостным трекингом.",
    "category": "tracking",
    "categoryLabel": "Трекинг",
    "package": "aex",
    "minAe": "2021",
    "version": "v2024.5",
    "size": "280 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1t-mMID-pjZcd3e5PnOvcqrZI3FJtkKSX/view?usp=drive_link",
    "badge": "Новый",
    "icon": "fas fa-bullseye",
    "tags": ["трекинг", "aex", "new"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "motion-tools-3",
    "name": "Motion Tools 3",
    "description": "Набор инструментов для анимации и управления проектом.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2021",
    "version": "v3.2.1",
    "size": "85 MB",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Новый",
    "icon": "fas fa-bolt",
    "tags": ["утилиты", "jsx", "new", "motion"],
    "updated": "Обновляется",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "newton",
    "name": "Newton",
    "description": "Физический движок для After Effects: гравитация, столкновения, динамика объектов.",
    "category": "animation",
    "categoryLabel": "Анимация",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1PKQSGpqQAEDukyiccwORV3eYCEWdvHSN/view?usp=drive_link",
    "badge": "Физика",
    "icon": "fas fa-atom",
    "tags": ["physics", "animation", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "omino",
    "name": "Omino",
    "description": "Набор небольших эффектов и инструментов для необычных визуализаций внутри After Effects.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2023",
    "version": "v2.2",
    "size": "925 KB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1ZBRR40rfj8tdTnjzlo4HYJ_1XCKXsz60/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-wind",
    "tags": ["эффекты", "aex", "popular"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2023+ / лучше AE 2022 и новее"
  },
  {
    "id": "optical-flares",
    "name": "Optical Flares",
    "description": "Плагин для создания линзовых бликов, световых вспышек и кинематографичных flare-эффектов.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1j9DlwhfFCFvhNTR5lYVfoPijbNUHuzsx/view?usp=drive_link",
    "badge": "Эффект",
    "icon": "fas fa-star",
    "tags": ["flare", "light", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "pixdither",
    "name": "PixDither",
    "description": "Эффект пиксельного дитеринга для стилизованного ретро-вида и цифровой графики.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/15ZkbLU4AFUFTKsFtOLTbdGhsD9vTtIMM/view?usp=drive_link",
    "badge": "Ретро",
    "icon": "fas fa-grip",
    "tags": ["pixel", "dither", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "polytrace",
    "name": "Polytrace",
    "description": "Инструмент для трассировки, векторизации и стилизации контуров.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2021",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1siauiMI2H5R4IyPJ2gxjU36fsxXvskhc/view?usp=drive_link",
    "badge": "Утилита",
    "icon": "fas fa-bezier-curve",
    "tags": ["trace", "vector", "jsx"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "red-giant",
    "name": "Red Giant",
    "description": "Комплект плагинов для цветокоррекции, визуальных эффектов и кинематографичного вида видео.",
    "category": "suite",
    "categoryLabel": "Комплект",
    "package": "aex",
    "minAe": "2021",
    "version": "v2024",
    "size": "1.2 GB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1SZaCDICiOB2cWzMSuZVGl9U5u8oRauW5/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-gem",
    "tags": ["комплект", "aex", "popular"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "red-giant-shooter",
    "name": "Red Giant Shooter",
    "description": "Инструмент Red Giant для работы с материалами, синхронизацией и подготовкой видеофайлов.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2022",
    "version": "v1.5.3",
    "size": "32 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1SZaCDICiOB2cWzMSuZVGl9U5u8oRauW5/view?usp=drive_link",
    "badge": "Утилита",
    "icon": "fas fa-camera",
    "tags": ["red giant", "shooter", "утилиты"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2022+ / лучше AE 2022 и новее"
  },
  {
    "id": "rsmb",
    "name": "RSMB",
    "description": "ReelSmart Motion Blur добавляет реалистичное размытие движения к видеозаписям и анимации.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "v6.2.0",
    "size": "45 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1N2LpqPtnmo68cjE7JaTs5nCspR2B4RwJ/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-wind",
    "tags": ["эффекты", "aex", "popular", "motion", "blur"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "saber",
    "name": "Saber",
    "description": "Создавайте световые мечи, неоновые надписи, энергетические эффекты и лазерные лучи с полным контролем.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2019",
    "version": "v2.1.0",
    "size": "18 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1gHqIG88EmMeiBXbcMawqsE5q5efoVN5I/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-jedi",
    "tags": ["эффекты", "aex", "popular"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2019+ / лучше AE 2022 и новее"
  },
  {
    "id": "shadow-studio-3",
    "name": "Shadow Studio 3",
    "description": "Создание реалистичных теней для 2D и 3D объектов с продвинутыми настройками света и перспективы.",
    "category": "3d",
    "categoryLabel": "3D",
    "package": "aex",
    "minAe": "2020",
    "version": "v3.0.5",
    "size": "65 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1qfWPtSQuOElGVADNDLLZyQUoba4UcfuV/view?usp=drive_link",
    "badge": "3D",
    "icon": "fas fa-cube",
    "tags": ["3d", "aex"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "signal",
    "name": "Signal",
    "description": "Инструмент для процедурной анимации, повторяющихся сигналов и управления движением.",
    "category": "animation",
    "categoryLabel": "Анимация",
    "package": "jsx",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1IgYLwYH-HJdJ06fM2mbyXFtXBGHVY5zR/view?usp=drive_link",
    "badge": "Анимация",
    "icon": "fas fa-signal",
    "tags": ["animation", "signal", "jsx"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "topaz-video-enhance",
    "name": "Topaz Video Enhance",
    "description": "Инструмент для улучшения, масштабирования и восстановления видео с применением AI-обработки.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "app",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/15y8xAdc1huXTf8Vemb_-dQ8vyqSRj1gW/view?usp=drive_link",
    "badge": "AI",
    "icon": "fas fa-up-right-and-down-left-from-center",
    "tags": ["ai", "upscale", "video"],
    "updated": "12.06.2026",
    "compatibility": "Отдельная программа / совместимо с монтажным пайплайном"
  },
  {
    "id": "tracery",
    "name": "Tracery",
    "description": "Инструмент для работы с трассировкой, линиями и стилизованной анимацией контуров.",
    "category": "animation",
    "categoryLabel": "Анимация",
    "package": "jsx",
    "minAe": "2020",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/178XAKNo1sMIVvOzSNGBgvhRBOW7etBx3/view?usp=drive_link",
    "badge": "Анимация",
    "icon": "fas fa-route",
    "tags": ["trace", "animation", "jsx"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "twitch",
    "name": "Twitch",
    "description": "Создание эффектов тряски камеры, глитчей и хаотичной анимации с помощью простых контроллеров.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2018",
    "version": "v5.2.1",
    "size": "8.5 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1tNym4KYR8jc_1N_02WOdyz_Yf1SmO0g7/view?usp=drive_link",
    "badge": "Эффект",
    "icon": "fas fa-tv",
    "tags": ["эффекты", "aex", "glitch"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2018+ / лучше AE 2022 и новее"
  },
  {
    "id": "twixtor",
    "name": "Twixtor",
    "description": "Один из самых известных плагинов для Adobe After Effects, позволяющий плавно изменять скорость видео.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "v8.1.1",
    "size": "31.4 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1Ql_Lc0ouKvY06qOolS5gh19DcpMTa1G_/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-magic",
    "tags": ["эффекты", "aex", "popular", "slow motion"],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "vc-color-vibrance",
    "name": "VC Color Vibrance",
    "description": "Плагин Video Copilot для цветного свечения, ярких масок и стилизованной графики.",
    "category": "color",
    "categoryLabel": "Цвет",
    "package": "aex",
    "minAe": "2019",
    "version": "Обновляется",
    "size": "Обновляется",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1xHQRrIQ-GX_kX3rxYpI9ZZ7hu25MSJyP/view?usp=drive_link",
    "badge": "Цвет",
    "icon": "fas fa-palette",
    "tags": ["color", "vibrance", "aex"],
    "updated": "12.06.2026",
    "compatibility": "After Effects 2019+ / лучше AE 2022 и новее"
  }
];
