window.AE_PLUGINS = [
  {
    "id": "twixtor",
    "name": "Twixtor",
    "description": "это один из самых известных плагинов для Adobe After Effects который позволяет плавно изменять скорость видео.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "v8.1.1",
    "size": "31.4 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1Ql_Lc0ouKvY06qOolS5gh19DcpMTa1G_/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-magic",
    "tags": [
      "эффекты",
      "aex",
      "popular"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "motion-tools-3",
    "name": "Motion Tools 3",
    "description": "Набор инструментов для анимации и управления проектом.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2021",
    "version": "v3.2.1",
    "size": "85 MB",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Новый",
    "icon": "fas fa-bolt",
    "tags": [
      "утилиты",
      "jsx",
      "new",
      "motion"
    ],
    "updated": "Обновляется",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "easecopy-2-0",
    "name": "EaseCopy 2.0",
    "description": "Копирование и вставка кривых анимации между ключевыми кадрами.",
    "category": "script",
    "categoryLabel": "Скрипты",
    "package": "jsx",
    "minAe": "2019",
    "version": "v2.0.8",
    "size": "12 MB",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Скрипт",
    "icon": "fas fa-wave-square",
    "tags": [
      "скрипты",
      "jsx"
    ],
    "updated": "Обновляется",
    "compatibility": "After Effects 2019+ / лучше AE 2022 и новее"
  },
  {
    "id": "film-damage-pack",
    "name": "Film Damage Pack",
    "description": "Эффекты старой пленки: царапины, пыль, зернистость, мерцание.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "ffx",
    "minAe": "2020",
    "version": "v1.5.3",
    "size": "210 MB",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Эффект",
    "icon": "fas fa-video",
    "tags": [
      "эффекты",
      "ffx"
    ],
    "updated": "Обновляется",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "fxconsole",
    "name": "FXConsole",
    "description": "это маленькая утилита с одной главной функцией — быстрый вызов и добавление любого эффекта из Adobe After Effects.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2022",
    "version": "v1.0.5",
    "size": "1.4 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/14hDha5z5quu9WeH_FEJCBPRYbunBiN-8/view?usp=drive_link",
    "badge": "Утилита",
    "icon": "fas fa-layer-group",
    "tags": [
      "утилиты",
      "jsx"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2022+ / лучше AE 2022 и новее"
  },
  {
    "id": "omino",
    "name": "Omino",
    "description": "Omino — это небольшие эффекты и инструменты (плагины) для After Effects, разработанные автором David Van Brink для создания визуальных эффектов, генеративного кода и необычных визуализаций внутри AE.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2023",
    "version": "v2.2",
    "size": "925 KB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1ZBRR40rfj8tdTnjzlo4HYJ_1XCKXsz60/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-wind",
    "tags": [
      "эффекты",
      "aex",
      "popular"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2023+ / лучше AE 2022 и новее"
  },
  {
    "id": "rsmb",
    "name": "RSMB",
    "description": "ReelSmart Motion Blur - добавляет реалистичное размытие в движении к видеозаписям, где его не было изначально.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "v6.2.0",
    "size": "45 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1N2LpqPtnmo68cjE7JaTs5nCspR2B4RwJ/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-wind",
    "tags": [
      "эффекты",
      "aex",
      "popular",
      "motion",
      "blur"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "mocha-pro",
    "name": "Mocha Pro",
    "description": "Мощный инструмент для трекинга, стабилизации и ротоскопинга с плоскостным трекингом.",
    "category": "tracking",
    "categoryLabel": "Трекинг",
    "package": "aex",
    "minAe": "2021",
    "version": "v2024.5",
    "size": "280 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1t-mMID-pjZcd3e5PnOvcqrZI3FJtkKSX/view?usp=drive_link",
    "badge": "Новый",
    "icon": "fas fa-bullseye",
    "tags": [
      "трекинг",
      "aex",
      "new"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "saber",
    "name": "Saber",
    "description": "Создавайте световые мечи, неоновые надписи, энергетические эффекты и лазерные лучи с полным контролем.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2019",
    "version": "v2.1.0",
    "size": "18 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1gHqIG88EmMeiBXbcMawqsE5q5efoVN5I/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-jedi",
    "tags": [
      "эффекты",
      "aex",
      "popular"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2019+ / лучше AE 2022 и новее"
  },
  {
    "id": "shadow-studio-3",
    "name": "Shadow Studio 3",
    "description": "Создание реалистичных теней для 2D и 3D объектов с продвинутыми настройками света и перспективы.",
    "category": "3d",
    "categoryLabel": "3D",
    "package": "aex",
    "minAe": "2020",
    "version": "v3.0.5",
    "size": "65 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1qfWPtSQuOElGVADNDLLZyQUoba4UcfuV/view?usp=drive_link",
    "badge": "3D",
    "icon": "fas fa-box-shadow",
    "tags": [
      "3d",
      "aex"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "red-giant",
    "name": "Red Giant",
    "description": "Комплект плагинов для цветокоррекции, визуальных эффектов и кинематографичного вида видео.",
    "category": "suite",
    "categoryLabel": "Комплект",
    "package": "aex",
    "minAe": "2021",
    "version": "v2024",
    "size": "1.2 GB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1SZaCDICiOB2cWzMSuZVGl9U5u8oRauW5/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-gem",
    "tags": [
      "комплект",
      "aex",
      "popular"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "shooter",
    "name": "Shooter",
    "description": "Инструмент для экспорта рендеров с поддержкой множества кодеков и пресетов.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2022",
    "version": "v1.5.3",
    "size": "32 MB",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Утилита",
    "icon": "fas fa-camera",
    "tags": [
      "утилиты",
      "jsx"
    ],
    "updated": "Обновляется",
    "compatibility": "After Effects 2022+ / лучше AE 2022 и новее"
  },
  {
    "id": "twich",
    "name": "Twich",
    "description": "Создание эффектов тряски камеры, глитчей и хаотичной анимации с помощью простых контроллеров.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2018",
    "version": "v5.2.1",
    "size": "8.5 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1tNym4KYR8jc_1N_02WOdyz_Yf1SmO0g7/view?usp=drive_link",
    "badge": "Эффект",
    "icon": "fas fa-tv",
    "tags": [
      "эффекты",
      "aex"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2018+ / лучше AE 2022 и новее"
  },
  {
    "id": "influx",
    "name": "Influx",
    "description": "Инструмент для создания продвинутых частиц, жидкостей и динамических симуляций.",
    "category": "particles",
    "categoryLabel": "Частицы",
    "package": "aex",
    "minAe": "2023",
    "version": "v1.8.0",
    "size": "120 MB",
    "status": "updating",
    "downloadUrl": "#",
    "badge": "Новый",
    "icon": "fas fa-water",
    "tags": [
      "частицы",
      "aex",
      "new"
    ],
    "updated": "Обновляется",
    "compatibility": "After Effects 2023+ / лучше AE 2022 и новее"
  },
  {
    "id": "flow",
    "name": "Flow",
    "description": "Плагин для создания и управления кривыми анимации с интуитивным интерфейсом.",
    "category": "utility",
    "categoryLabel": "Утилиты",
    "package": "jsx",
    "minAe": "2019",
    "version": "v2.0.1",
    "size": "4.2 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1KRXEiGgy4XFaOIyMMqDtBG702uljfu43/view?usp=drive_link",
    "badge": "Утилита",
    "icon": "fas fa-wave-square",
    "tags": [
      "утилиты",
      "jsx"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2019+ / лучше AE 2022 и новее"
  },
  {
    "id": "brokeh",
    "name": "Brokeh",
    "description": "Создание эффектов боке и размытия с художественным контролем над формой и интенсивностью.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2020",
    "version": "v1.1.0",
    "size": "22 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1bjfHjjp4FQSr1yaMDhz8yL_e1DB6SFj-/view?usp=drive_link",
    "badge": "Эффект",
    "icon": "fas fa-tint",
    "tags": [
      "эффекты",
      "aex"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2020+ / лучше AE 2022 и новее"
  },
  {
    "id": "bcc-sapphire",
    "name": "BCC Sapphire",
    "description": "Коллекция из более чем 270 профессиональных эффектов для цветокоррекции, стилизации и переходов.",
    "category": "effects",
    "categoryLabel": "Эффекты",
    "package": "aex",
    "minAe": "2021",
    "version": "v2024.01",
    "size": "850 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1gXX0MUQ-Cz4S75TsW4RtHnstO1CTaXog/view?usp=drive_link",
    "badge": "Популярный",
    "icon": "fas fa-sparkles",
    "tags": [
      "эффекты",
      "aex",
      "popular"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2021+ / лучше AE 2022 и новее"
  },
  {
    "id": "bcc-continuum",
    "name": "BCC Continuum",
    "description": "Полный набор плагинов для визуальных эффектов, включая ретушь, стилизацию и анимацию.",
    "category": "suite",
    "categoryLabel": "Комплект",
    "package": "aex",
    "minAe": "2022",
    "version": "v2024",
    "size": "2.1 GB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1wjiCMn2cOGR0WDy1Iy2jKUhKltJN_Vl-/view?usp=drive_link",
    "badge": "Комплект",
    "icon": "fas fa-infinity",
    "tags": [
      "комплект",
      "aex"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2022+ / лучше AE 2022 и новее"
  },
  {
    "id": "autosway",
    "name": "AutoSway",
    "description": "Автоматическая анимация колебаний для текста, объектов и слоев с реалистичной физикой.",
    "category": "animation",
    "categoryLabel": "Анимация",
    "package": "jsx",
    "minAe": "2018",
    "version": "v2.3.0",
    "size": "3.5 MB",
    "status": "available",
    "downloadUrl": "https://drive.google.com/file/d/1OMLa4wbLGeJ760CqjPeOa3ooXG0uNpD1/view?usp=drive_link",
    "badge": "Скрипт",
    "icon": "fas fa-random",
    "tags": [
      "анимация",
      "jsx"
    ],
    "updated": "15.05.2026",
    "compatibility": "After Effects 2018+ / лучше AE 2022 и новее"
  }
];
