services:
  - type: web
    name: null-object-ae
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SITE_URL
        value: https://null-object-ae.onrender.com
      - key: TELEGRAM_URL
        value: https://t.me/ae_plugins_vault
